/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CostRouteImport } from './routes/cost'
import { Route as HowRouteImport } from './routes/how'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as LiveRouteImport } from './routes/live'
import { Route as OperateRouteImport } from './routes/operate'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QuoteRouteImport } from './routes/quote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateRoute = OperateRouteImport.update({
  id: '/operate',
  path: '/operate',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/cost': typeof CostRoute
  '/how': typeof HowRoute
  '/industries': typeof IndustriesRoute
  '/live': typeof LiveRoute
  '/operate': typeof OperateRoute
  '/playbook': typeof PlaybookRoute
  '/products': typeof ProductsRoute
  '/quote': typeof QuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/cost': typeof CostRoute
  '/how': typeof HowRoute
  '/industries': typeof IndustriesRoute
  '/live': typeof LiveRoute
  '/operate': typeof OperateRoute
  '/playbook': typeof PlaybookRoute
  '/products': typeof ProductsRoute
  '/quote': typeof QuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/cost': typeof CostRoute
  '/how': typeof HowRoute
  '/industries': typeof IndustriesRoute
  '/live': typeof LiveRoute
  '/operate': typeof OperateRoute
  '/playbook': typeof PlaybookRoute
  '/products': typeof ProductsRoute
  '/quote': typeof QuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cost'
    | '/how'
    | '/industries'
    | '/live'
    | '/operate'
    | '/playbook'
    | '/products'
    | '/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/cost'
    | '/how'
    | '/industries'
    | '/live'
    | '/operate'
    | '/playbook'
    | '/products'
    | '/quote'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cost'
    | '/how'
    | '/industries'
    | '/live'
    | '/operate'
    | '/playbook'
    | '/products'
    | '/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CostRoute: typeof CostRoute
  HowRoute: typeof HowRoute
  IndustriesRoute: typeof IndustriesRoute
  LiveRoute: typeof LiveRoute
  OperateRoute: typeof OperateRoute
  PlaybookRoute: typeof PlaybookRoute
  ProductsRoute: typeof ProductsRoute
  QuoteRoute: typeof QuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate': {
      id: '/operate'
      path: '/operate'
      fullPath: '/operate'
      preLoaderRoute: typeof OperateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CostRoute: CostRoute,
  HowRoute: HowRoute,
  IndustriesRoute: IndustriesRoute,
  LiveRoute: LiveRoute,
  OperateRoute: OperateRoute,
  PlaybookRoute: PlaybookRoute,
  ProductsRoute: ProductsRoute,
  QuoteRoute: QuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
